### ISSUE TITLE
Enhanced Editor - enabled map pop ups with attribute inspector form is open

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#444]
Disable selection of editing features when the attribute inspector is open, this would allow the user to look at and apply info from other features into the edit.

**Comment by camtran** [comment]
Done. Please review @MikeMillerGIS Thanks.

**Comment by MikeMillerGIS** [comment]
Always enable map pop up when attribute is open, not only after a attribute change.

**Comment by camtran** [comment]
Map pop up is now always open when the attribute inspector form is open.  Please review. Thanks.

**Comment by MikeMillerGIS** [comment]
still having problems with this.  The following workflow does not produce a pop up
1:  Select a point template
2:  Add Point
3:  When the attribute inspector is open, click on existing feature, no pop up
4:  Close or open other widget
5:  Reopen editing widget
6:  Click on existing feature, pop up is now shown
![enhancededitorpopup](https://cloud.githubusercontent.com/assets/2707285/13759996/485e2c9a-ea07-11e5-9ac4-e84ef84d832f.gif)

**Comment by camtran** [comment]
I currently use a tolerance in pixel = 20 when constructing the extent of the point to perform feature selection. We can increase it if need. Or perhaps we can put it in config?

**Comment by MikeMillerGIS** [comment]
Verified
